package com.mycompany.mvnspringhibernate.model.pojo;
// Generated 18.12.2015 15:12:44 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Country generated by hbm2java
 */
public class Country  implements java.io.Serializable {


     private Short countryId;
     private String country;
     private Date lastUpdate;

    public Country() {
    }

    public Country(String country, Date lastUpdate) {
       this.country = country;
       this.lastUpdate = lastUpdate;
    }
   
    public Short getCountryId() {
        return this.countryId;
    }
    
    public void setCountryId(Short countryId) {
        this.countryId = countryId;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }




}


